# Используем лёгкий образ с Python 3.10
FROM python:3.10-slim

# Рабочая директория в контейнере
WORKDIR /app

# Копируем и устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код бота и скрипта
COPY . .

# По умолчанию запускаем бота
CMD ["python", "bot.py"]